// The only product actually in stock. Placeholder reviews are never attached
// to it — inventing testimonials for a real product you sell would be
// misleading, so it starts with none.
export const REAL_PRODUCT_SLUG = "hope-5-5l-a1";

// Slug this product previously used in the catalog. The bootstrap route
// renames it in place so the existing row is updated rather than orphaned.
export const RENAMED_FROM = { from: "bat-5", to: REAL_PRODUCT_SLUG };

export const products = [
  {
    slug: REAL_PRODUCT_SLUG,
    name: "باتری لیتیوم ۵.۵ کیلووات‌ساعت گروات مدل Hope 5.5L-A1",
    brand: "Growatt",
    category: "باتری لیتیوم",
    price: 240_000_000,
    rating: 5,
    reviewCount: 0,
    stock: true,
    badge: "موجود",
    power: "۵.۵ کیلووات‌ساعت",
    voltage: "۵۱.۲ ولت",
    warranty: "۵ سال",
    extra: "عمق دشارژ ۹۳٪",
    description:
      "باتری لیتیوم فسفات آهن (LiFePO4) با ظرفیت ۵.۵ کیلووات‌ساعت و عمق دشارژ ۹۳٪. طراحی جمع‌وجور و نصب آسان، چگالی انرژی و بازده بالا، ایمنی بالای سلول‌های LiFePO4 و امکان اتصال موازی تا ۱۲ پک. مناسب سیستم‌های خورشیدی خانگی و تجاری کوچک.",
    image: "/img/prod-bat-wall.png",
    specs: [
      { k: "ولتاژ نامی", v: "۵۱.۲ ولت" },
      { k: "ظرفیت اسمی", v: "۵.۵ کیلووات‌ساعت" },
      { k: "ظرفیت قابل استفاده", v: "۵.۱۲ کیلووات‌ساعت" },
      { k: "محدوده ولتاژ کاری", v: "۴۰ تا ۵۸.۴ ولت" },
      { k: "حداکثر جریان دشارژ", v: "۱۰۰ آمپر" },
      { k: "جریان دشارژ پیک", v: "۱۲۰ آمپر / ۳ ثانیه" },
      { k: "حداکثر جریان شارژ", v: "۱۰۰ آمپر" },
      { k: "عمق دشارژ (DoD)", v: "۹۳٪" },
      { k: "طول عمر چرخه", v: "بیش از ۶۰۰۰ سیکل (۲۵ درجه، ۰.۲C)" },
      { k: "اتصال موازی", v: "حداکثر ۱۲ پک" },
      { k: "پورت ارتباطی", v: "CAN / RS485" },
      { k: "ابعاد (عرض×عمق×ارتفاع)", v: "۴۴۰ × ۵۴۰ × ۱۳۰.۵ میلی‌متر" },
      { k: "وزن", v: "۴۵ ±۱ کیلوگرم" },
      { k: "درجه حفاظت", v: "IP20" },
      { k: "دمای شارژ", v: "۰ تا +۵۵ درجه سانتی‌گراد" },
      { k: "دمای دشارژ", v: "−۲۰ تا +۵۵ درجه سانتی‌گراد" },
      { k: "گارانتی", v: "۵ سال" },
      { k: "استانداردها", v: "CE (EMC)، UN38.3، MSDS، RoHS" },
    ],
  },
  {
    slug: "inv-hyb-5",
    name: "اینورتر هیبرید ۵ کیلووات مدل SPH 5000",
    brand: "Growatt",
    category: "اینورتر",
    price: 78_000_000,
    rating: 5,
    reviewCount: 41,
    stock: false,
    badge: null,
    power: "۵ کیلووات",
    voltage: "۴۸ ولت DC",
    warranty: "۵ سال",
    extra: "MPPT دوگانه",
    description:
      "اینورتر هیبرید سه‌کاره برای سیستم‌های خانگی: اتصال به شبکه، شارژ باتری و تأمین بار در قطعی برق. با دو ورودی MPPT و پشتیبانی از اپلیکیشن مانیتورینگ.",
    image: "/img/prod-inv-hybrid.png",
    specs: null,
  },
  {
    slug: "inv-ong-10",
    name: "اینورتر آنگرید ۱۰ کیلووات سه‌فاز SG10RT",
    brand: "Sungrow",
    category: "اینورتر",
    price: 132_000_000,
    rating: 5,
    reviewCount: 18,
    stock: false,
    badge: null,
    power: "۱۰ کیلووات",
    voltage: "۳۸۰ ولت AC",
    warranty: "۱۰ سال",
    extra: "بازده ۹۸.۴٪",
    description:
      "اینورتر آنگرید سه‌فاز مناسب کارگاه و ساختمان‌های اداری، با بازده اروپایی ۹۸.۴٪ و قابلیت پایش تولید از راه دور.",
    image: "/img/prod-inv-3ph.png",
    specs: null,
  },
  {
    slug: "bat-14",
    name: "باتری لیتیوم ۱۴.۳ کیلووات‌ساعت رک‌مونت HOPE 14.3L",
    brand: "Growatt",
    category: "باتری لیتیوم",
    price: 245_000_000,
    rating: 5,
    reviewCount: 12,
    stock: false,
    badge: null,
    power: "۱۴.۳ کیلووات‌ساعت",
    voltage: "۵۱.۲ ولت",
    warranty: "۱۰ سال",
    extra: "رک ۱۹ اینچ",
    description:
      "بانک باتری رک‌مونت برای سیستم‌های خانگی بزرگ و تجاری کوچک، با مانیتورینگ سلولی و خنک‌کاری غیرفعال.",
    image: "/img/prod-bat-rack.png",
    specs: null,
  },
  {
    slug: "bat-10",
    name: "باتری لیتیوم ۱۰ کیلووات‌ساعت پک صنعتی",
    brand: "Pylontech",
    category: "باتری لیتیوم",
    price: 178_000_000,
    rating: 4,
    reviewCount: 9,
    stock: false,
    badge: null,
    power: "۱۰ کیلووات‌ساعت",
    voltage: "۵۱.۲ ولت",
    warranty: "۸ سال",
    extra: "IP55",
    description:
      "پک باتری صنعتی با درجه حفاظت IP55 برای نصب در محیط نیمه‌باز و ایستگاه‌های پمپاژ.",
    image: "/img/prod-bat-ind.png",
    specs: null,
  },
  {
    slug: "pkg-3",
    name: "پکیج کامل خورشیدی خانگی ۳ کیلووات",
    brand: "Ashianeh",
    category: "سیستم کامل",
    price: 320_000_000,
    rating: 5,
    reviewCount: 63,
    stock: false,
    badge: null,
    power: "۳ کیلووات",
    voltage: "۲۲۰ ولت",
    warranty: "۵ سال",
    extra: "با نصب",
    description:
      "پکیج آماده شامل شش پنل ۶۱۰ واتی، اینورتر هیبرید، باتری ۵ کیلووات‌ساعت، سازه و کابل‌کشی، همراه با نصب و راه‌اندازی.",
    image: "/img/prod-pkg-home.png",
    specs: null,
  },
  {
    slug: "pkg-20",
    name: "پکیج صنعتی خورشیدی ۲۰ کیلووات سقف کارخانه",
    brand: "Ashianeh",
    category: "سیستم کامل",
    price: 1_850_000_000,
    rating: 5,
    reviewCount: 7,
    stock: false,
    badge: null,
    power: "۲۰ کیلووات",
    voltage: "۳۸۰ ولت",
    warranty: "۱۰ سال",
    extra: "با پیش‌فاکتور رسمی",
    description:
      "راهکار کامل کاهش هزینه برق صنعتی: آرایه ۳۳ پنلی، اینورتر سه‌فاز، پایش تولید و امکان قرارداد خرید تضمینی برق مازاد.",
    image: "/img/prod-pkg-ind.png",
    specs: null,
  },
  {
    slug: "wind-3",
    name: "توربین بادی ۳ کیلووات محور افقی",
    brand: "Windzilla",
    category: "توربین بادی",
    price: 210_000_000,
    rating: 4,
    reviewCount: 5,
    stock: false,
    badge: null,
    power: "۳ کیلووات",
    voltage: "۴۸ ولت DC",
    warranty: "۳ سال",
    extra: "باد شروع ۲.۵ m/s",
    description:
      "توربین بادی کوچک برای مناطق بادخیز و سیستم‌های ترکیبی خورشید-باد، با پره‌های کامپوزیت و ترمز الکترومغناطیسی.",
    image: "/img/prod-wind.png",
    specs: null,
  },
  {
    slug: "ev-11",
    name: "شارژر خودرو برقی ۱۱ کیلووات دیواری",
    brand: "Zaptec",
    category: "شارژر خودرو برقی",
    price: 62_000_000,
    rating: 5,
    reviewCount: 22,
    stock: false,
    badge: null,
    power: "۱۱ کیلووات",
    voltage: "۳۸۰ ولت AC",
    warranty: "۳ سال",
    extra: "Type 2 · اپلیکیشن",
    description:
      "شارژر هوشمند دیواری با کنترل مصرف، زمان‌بندی شارژ در ساعات کم‌باری و هماهنگی با تولید پنل خورشیدی.",
    image: "/img/prod-ev.png",
    specs: null,
  },
  {
    slug: "sw-300",
    name: "آبگرمکن خورشیدی ۳۰۰ لیتری لوله خلأ",
    brand: "Sunrise",
    category: "آبگرمکن خورشیدی",
    price: 48_000_000,
    rating: 4,
    reviewCount: 31,
    stock: false,
    badge: null,
    power: "۳۰۰ لیتر",
    voltage: "—",
    warranty: "۵ سال",
    extra: "۲۴ لوله خلأ",
    description:
      "آبگرمکن خورشیدی با مخزن استیل و لوله‌های خلأ، مناسب خانه چهار تا شش نفره؛ بدون مصرف برق.",
    image: "/img/prod-heater.png",
    specs: null,
  },
  {
    slug: "pump-15",
    name: "پمپ آب خورشیدی ۱.۵ کیلووات چاه عمیق",
    brand: "Lorentz",
    category: "پمپ آب خورشیدی",
    price: 71_000_000,
    rating: 4,
    reviewCount: 14,
    stock: false,
    badge: null,
    power: "۱.۵ کیلووات",
    voltage: "۷۲ ولت DC",
    warranty: "۲ سال",
    extra: "ارتفاع ۸۰ متر",
    description:
      "پمپ شناور DC با درایو خورشیدی، بدون نیاز به باتری؛ برای آبیاری و آبرسانی دام در مناطق دور از شبکه.",
    image: "/img/prod-pump.png",
    specs: null,
  },
  {
    slug: "pkg-camp",
    name: "پکیج برق خورشیدی کمپر و آفرود ۱.۵ کیلووات",
    brand: "Ashianeh",
    category: "سیستم کامل",
    price: 96_000_000,
    rating: 4,
    reviewCount: 38,
    stock: false,
    badge: null,
    power: "۱.۵ کیلووات",
    voltage: "۱۲ ولت DC",
    warranty: "۲ سال",
    extra: "قابل حمل",
    description:
      "مجموعه قابل حمل شامل پنل تاشو، اینورتر ۲۰۰۰ وات، باتری ۱۰۰ آمپرساعت و شارژر خودرو برای سفر و کمپینگ.",
    image: "/img/prod-camp.png",
    specs: null,
  },
];

export const genericReviews = [
  { author: "مهدی ر.", rating: 5, comment: "دو ماه است نصب شده. در قطعی‌های تابستان کل خانه بدون وقفه کار کرد. تنظیم اپلیکیشن ساده بود." },
  { author: "شرکت آریا صنعت", rating: 5, comment: "برای کارگاه ۶۰۰ متری گرفتیم. پیش‌فاکتور رسمی سریع صادر شد و نصب طبق زمان‌بندی انجام شد." },
  { author: "سحر ک.", rating: 4, comment: "کیفیت کالا خوب است. ارسال یک روز دیرتر از موعد رسید ولی پشتیبانی مرتب اطلاع می‌داد." },
];
